name: chaility
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: "0.4.4+3"
  firebase_analytics: "5.0.11"
  firebase_auth: "0.15.4"
  firebase_storage: "3.1.1"
  cloud_firestore: "0.13.4+2"
  provider: "4.0.4"
  image_picker: "0.6.3+4"
  timeago: "2.0.26"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
